### PR TITLE
fixed wanings uninitialized value when skip_bind(1)

### PR DESCRIPTION
**Pull request by Hirofumi-Narita**
see also https://github.com/xaicron/p5-DBIx-QueryLog/issues/19

### CODE REVIEW

**Comment by xaicron** [comment]
Thank you pull request :)
Could you write test-code?

**Comment by Hirofumi-Narita** [comment]
I understand. Thank you.

**Comment by Hirofumi-Narita** [comment]
I wrote a test for skip_bind.
Please let me know if you have advice or questions.

**Comment by xaicron** [comment]
Could you writing test t/(mysql|pg)/12_do_skip_bind.t ?

**Comment by Hirofumi-Narita** [comment]
OK. I understand. Thank you for review.

**Comment by Hirofumi-Narita** [comment]
I wrote  test t/(mysql|pg)/12_do_skip_bind.t.
Please let me know if you have advice or questions again.

**Comment by xaicron** [comment]
Thank you! great works!!

**Comment by Hirofumi-Narita** [comment]
Thank you!

**Pull request merged**
